"""create users and learning_profiles

Revision ID: 01a7a759cfed
Revises: 
Create Date: 2026-08-16 16:37:38.733241

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01a7a759cfed'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('learning_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_grammar', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('level_vocabulary', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('level_reading', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('level_listening', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('level_speaking', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('level_writing', sa.Enum('A1', 'A2', 'B1', 'B2', name='cefr_level'), nullable=True),
    sa.Column('priority_goals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('placement_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    sa.Enum(name='cefr_level').drop(op.get_bind(), checkfirst=True)
