"""add exercise engine tables

Revision ID: 0ea1f940faab
Revises: 34f7e7604da3
Create Date: 2026-08-16 21:14:56.888914

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ea1f940faab'
down_revision: str | Sequence[str] | None = '34f7e7604da3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('exercise_type', sa.Enum('MULTIPLE_CHOICE', 'SINGLE_CHOICE', 'FILL_BLANK', 'SENTENCE_ORDERING', 'MATCHING', 'TRANSLATION', 'ERROR_CORRECTION', 'READING_COMPREHENSION', 'LISTENING_COMPREHENSION', 'DICTATION', 'WRITING', 'SPEAKING', name='exercise_type'), nullable=False),
    sa.Column('skill', sa.Enum('GRAMMAR', 'VOCABULARY', 'READING', 'LISTENING', 'WRITING', 'SPEAKING', name='skill'), nullable=False),
    # cefr_level already exists (created by 01a7a759cfed) — reused here, not recreated.
    sa.Column('difficulty', postgresql.ENUM('A1', 'A2', 'B1', 'B2', name='cefr_level', create_type=False), nullable=False),
    sa.Column('prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=True),
    sa.Column('vocabulary_id', sa.UUID(), nullable=True),
    sa.Column('is_placement_item', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_index('ix_exercises_skill_difficulty', 'exercises', ['skill', 'difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('submitted_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source', sa.Enum('LESSON_PRACTICE', 'PLACEMENT_TEST', 'REVIEW', name='exercise_attempt_source'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercise_attempts_user_exercise', 'exercise_attempts', ['user_id', 'exercise_id'], unique=False)
    op.create_index('ix_exercise_attempts_user_source', 'exercise_attempts', ['user_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_attempts_user_source', table_name='exercise_attempts')
    op.drop_index('ix_exercise_attempts_user_exercise', table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index('ix_exercises_skill_difficulty', table_name='exercises')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
    sa.Enum(name='exercise_attempt_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='skill').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='exercise_type').drop(op.get_bind(), checkfirst=True)
