"""add course engine tables

Revision ID: 34f7e7604da3
Revises: 01a7a759cfed
Create Date: 2026-08-16 20:47:08.182894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34f7e7604da3'
down_revision: str | Sequence[str] | None = '01a7a759cfed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_topics_slug'), 'grammar_topics', ['slug'], unique=True)
    op.create_table('levels',
    sa.Column('id', sa.UUID(), nullable=False),
    # cefr_level already exists (created by 01a7a759cfed) — reused here, not recreated.
    sa.Column('code', postgresql.ENUM('A1', 'A2', 'B1', 'B2', name='cefr_level', create_type=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('order_index')
    )
    op.create_table('vocabulary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('headword', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_headword'), 'vocabulary', ['headword'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'order_index', name='uq_modules_level_order')
    )
    op.create_index(op.f('ix_modules_slug'), 'modules', ['slug'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'order_index', name='uq_lessons_module_order')
    )
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_table('lesson_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('block_type', sa.Enum('LEARNING_GOALS', 'CONTEXT', 'VOCABULARY', 'GRAMMAR', 'EXAMPLES', 'EXERCISES', 'READING', 'LISTENING', 'SPEAKING', 'HOMEWORK', 'REVIEW', name='lesson_block_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_lesson_blocks_lesson_order')
    )
    op.create_table('lesson_grammar_topics',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'grammar_topic_id')
    )
    op.create_table('lesson_vocabulary',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('lesson_id', 'vocabulary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_vocabulary')
    op.drop_table('lesson_grammar_topics')
    op.drop_table('lesson_blocks')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_modules_slug'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_vocabulary_headword'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_table('levels')
    op.drop_index(op.f('ix_grammar_topics_slug'), table_name='grammar_topics')
    op.drop_table('grammar_topics')
    # ### end Alembic commands ###
    sa.Enum(name='lesson_block_type').drop(op.get_bind(), checkfirst=True)
