"""add is_final_exam_item to exercises

Revision ID: 546ec3924bef
Revises: 4180c61c8a42
Create Date: 2026-08-30 15:13:05.386865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546ec3924bef'
down_revision: Union[str, Sequence[str], None] = '4180c61c8a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'exercises',
        sa.Column('is_final_exam_item', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'is_final_exam_item')
    # ### end Alembic commands ###
