"""add homework and homework_attempts tables

Revision ID: 7fc96518a067
Revises: d31c25ccb1b2
Create Date: 2026-08-18 16:01:09.800536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc96518a067'
down_revision: Union[str, Sequence[str], None] = 'd31c25ccb1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_homework_user_generated_at', 'homework', ['user_id', 'generated_at'], unique=False)
    op.create_table('homework_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('homework_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('submitted_text', sa.Text(), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_homework_attempts_homework', 'homework_attempts', ['homework_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_homework_attempts_homework', table_name='homework_attempts')
    op.drop_table('homework_attempts')
    op.drop_index('ix_homework_user_generated_at', table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
