"""add mistake and review item tables

Revision ID: d31c25ccb1b2
Revises: 0ea1f940faab
Create Date: 2026-08-16 22:30:08.555858

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd31c25ccb1b2'
down_revision: str | Sequence[str] | None = '0ea1f940faab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mistakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'REPEATED', 'IMPROVING', 'MASTERED', name='mistake_status'), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('incorrect_attempts', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grammar_topic_id', name='uq_user_mistakes_user_topic')
    )
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('VOCABULARY', 'GRAMMAR_TOPIC', 'EXERCISE', name='review_item_type'), nullable=False),
    sa.Column('vocabulary_id', sa.UUID(), nullable=True),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=True),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_items_user_due', 'review_items', ['user_id', 'due_at'], unique=False)
    op.create_index('uq_review_items_user_exercise', 'review_items', ['user_id', 'exercise_id'], unique=True, postgresql_where=sa.text('exercise_id IS NOT NULL'))
    op.create_index('uq_review_items_user_grammar_topic', 'review_items', ['user_id', 'grammar_topic_id'], unique=True, postgresql_where=sa.text('grammar_topic_id IS NOT NULL'))
    op.create_index('uq_review_items_user_vocabulary', 'review_items', ['user_id', 'vocabulary_id'], unique=True, postgresql_where=sa.text('vocabulary_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_items_user_vocabulary', table_name='review_items', postgresql_where=sa.text('vocabulary_id IS NOT NULL'))
    op.drop_index('uq_review_items_user_grammar_topic', table_name='review_items', postgresql_where=sa.text('grammar_topic_id IS NOT NULL'))
    op.drop_index('uq_review_items_user_exercise', table_name='review_items', postgresql_where=sa.text('exercise_id IS NOT NULL'))
    op.drop_index('ix_review_items_user_due', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('user_mistakes')
    # ### end Alembic commands ###
    sa.Enum(name='review_item_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='mistake_status').drop(op.get_bind(), checkfirst=True)
