"""add mini test flag, mini_test block type, level exam attempts

Revision ID: e494e8419353
Revises: 3e9f80024941
Create Date: 2026-08-19 19:20:12.563800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e494e8419353'
down_revision: Union[str, Sequence[str], None] = '3e9f80024941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_exam_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    # cefr_level already exists (created by 01a7a759cfed) — reused here, not recreated.
    sa.Column('level', postgresql.ENUM('A1', 'A2', 'B1', 'B2', name='cefr_level', create_type=False), nullable=False),
    sa.Column('exercise_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_level_exam_attempts_user_level', 'level_exam_attempts', ['user_id', 'level'], unique=False)
    op.add_column(
        'exercises',
        sa.Column('is_mini_test_item', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # SQLAlchemy's Enum() persists Python enum *member names*, not
    # `.value` (all existing lesson_block_type entries are upper-case,
    # e.g. 'LEARNING_GOALS' for BlockType.LEARNING_GOALS = "learning_goals") —
    # match that convention here, not the lower-case string value.
    op.execute("ALTER TYPE lesson_block_type ADD VALUE IF NOT EXISTS 'MINI_TEST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres has no `DROP VALUE` for enum types, so the 'mini_test' value
    # added to lesson_block_type in upgrade() is left in place on downgrade.
    op.drop_column('exercises', 'is_mini_test_item')
    op.drop_index('ix_level_exam_attempts_user_level', table_name='level_exam_attempts')
    op.drop_table('level_exam_attempts')
    # ### end Alembic commands ###
